'use strict';
// Showcials Orbit: public, unlisted rooms. No accounts, recording or analytics.
const http=require('node:http'), fs=require('node:fs'), path=require('node:path'), crypto=require('node:crypto');
let WS;try{WS=require('ws')}catch{WS=require('./showcials-roku-native-v10.1/vendor/ws.cjs')}
const {WebSocketServer}=WS, {NativeVoice}=require('./lib/native-voice');
const {TVSession}=require('./lib/tv-session');
const {applyRequestBudget}=require('./lib/request-budget');
const PORT=Number(process.env.PORT||7741), ROOT=__dirname;
const rooms=new Map(), rates=new Map(), audio=new Map();
const wss=new WebSocketServer({noServer:true,maxPayload:65536,perMessageDeflate:false});
const vss=new WebSocketServer({noServer:true,maxPayload:16384,perMessageDeflate:false});
const now=()=>Date.now(), id=()=>crypto.randomBytes(18).toString('hex');
const problem=(status,message)=>Object.assign(new Error(message),{status});
const text=(v,n)=>typeof v==='string'?v.replace(/[\x00-\x1f\x7f]/g,'').trim().slice(0,n):'';
function equal(a,b){if(typeof a!=='string'||typeof b!=='string')return false;const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function cleanCode(v){return text(v,48).toLowerCase().replace(/[^a-z0-9]/g,'')}
function rate(key,max,ms){const t=now();let a=rates.get(key);if(!a||t>=a.until){if(rates.size>10000)throw problem(503,'Please try again later.');a={count:0,until:t+ms};rates.set(key,a)}if(++a.count>max)throw problem(429,'Please slow down and try again in a moment.')}
function ip(req){return process.env.RAILWAY_ENVIRONMENT_ID?String(req.headers['x-forwarded-for']||req.socket.remoteAddress).split(',')[0].trim():req.socket.remoteAddress}
function originOK(req){if(!req.headers.origin)return true;try{const u=new URL(req.headers.origin);return (u.protocol==='https:'||u.protocol==='http:')&&u.host===req.headers.host}catch{return false}}
function headers(res){res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');res.setHeader('Permissions-Policy','microphone=(self), camera=(), geolocation=()');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; media-src 'self' blob: https:; connect-src 'self' https: wss: ws:; worker-src 'self' blob:; font-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'")}
function json(res,status,obj){if(res.destroyed||res.writableEnded)return;headers(res);res.setHeader('Cache-Control','no-store');res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(obj))}
function body(req){return new Promise((resolve,reject)=>{let n=0,b=[],done=false;const bad=e=>{if(!done){done=true;b=[];reject(e)}};req.on('data',x=>{n+=x.length;if(n>65536)return bad(problem(413,'Message too large.'));if(!done)b.push(x)});req.on('end',()=>{if(done)return;done=true;try{const x=JSON.parse(Buffer.concat(b).toString()||'{}');if(!x||typeof x!=='object'||Array.isArray(x))throw Error();resolve(x)}catch{reject(problem(400,'Invalid request.'))}});req.on('aborted',()=>bad(problem(400,'Request interrupted.')));req.on('error',()=>bad(problem(400,'Request interrupted.')))})}
function send(ws,p,binary=false){if(ws.readyState!==1||ws.bufferedAmount>262144)return false;try{ws.send(binary?p:JSON.stringify(p),{binary},e=>{if(e)ws.terminate()});return true}catch{return false}}
function list(r){return [...r.members.values()].map(m=>({id:m.id,name:m.name,kind:m.kind}))}
function voiceList(r){return [...audio.values()].filter(a=>a.room===r.slug).map(a=>({id:a.id,clientId:a.clientId,name:a.name,muted:a.muted})).concat(native.roster(r.slug))}
function snapshot(r,since=0){return {ok:true,epoch:r.epoch,seq:r.seq,ts:now(),hostId:r.hostId,sync:r.sync,tv:tv.state(r),members:list(r),moments:r.moments,events:r.events.filter(e=>e.seq>since)}}
function emit(r,type,data={}){const p={...data,v:2,type,room:r.slug,seq:++r.seq,ts:now()};r.events.push(p);if(r.events.length>300)r.events.shift();for(const m of r.members.values())if(m.ws)send(m.ws,p);for(const [key,poll] of r.polls){clearTimeout(poll.timer);r.polls.delete(key);json(poll.res,200,snapshot(r,poll.since))}r.lastActive=now();return p}
function rosterChanged(slug){const r=rooms.get(slug);if(!r)return;const p=emit(r,'voice_state',{roster:voiceList(r)});for(const [ws,a]of audio)if(a.room===slug)send(ws,p)}
const native=new NativeVoice({notify:rosterChanged,broadcast:(room,from,clientId,frame)=>{for(const[ws,a]of audio)if(a.room===room&&a.clientId!==clientId&&ws.bufferedAmount<64000){send(ws,{type:'voice_frame',from});send(ws,frame,true)}}});
const tv=new TVSession({emit});
const demo={type:'sync',mode:'native',mediaUrl:'/media/orbit.mp4',mediaTitle:'Orbit — an original Showcials motion study',format:'mp4',runtimeSec:24,positionSec:0,status:'paused',serverTime:0};
function createRoom(){if(rooms.size>=100)throw problem(503,'The cinema is busy. Please try again later.');const alphabet='abcdefghjkmnpqrstuvwxyz23456789';let code;do{code=[...crypto.randomBytes(8)].map(x=>alphabet[x%alphabet.length]).join('')}while(rooms.has(code));const r={slug:code,epoch:id(),seq:0,events:[],members:new Map(),polls:new Map(),hostId:null,moments:[],sync:{...demo,serverTime:now(),seq:0,ts:now()},lastActive:now()};rooms.set(code,r);return r}
function getRoom(code){const r=rooms.get(cleanCode(code));if(!r)throw problem(404,'That room was not found or has ended. Check the code, or start a new room.');return r}
function welcome(r,m){return {...snapshot(r),type:'welcome',clientId:m.id,nativeVoiceGrant:m.grant,since:r.seq,voice:voiceList(r)}}
function join(r,name,kind,ws=null){if(r.members.size>=12)throw problem(409,'This room is full (12 people).');const m={id:id(),grant:id(),name:text(name,32)||'Guest',kind:kind==='roku'?'roku':'browser',lastSeen:now(),ws,acks:new Map()};r.members.set(m.id,m);if(!r.hostId)r.hostId=m.id;emit(r,'member_joined',{name:m.name,members:list(r),hostId:r.hostId});emit(r,'host_state',{hostId:r.hostId});return m}
function member(r,key,grant){const m=r.members.get(key);if(!m)throw problem(401,'Room session expired. Please rejoin.');if(!equal(grant,m.grant))throw problem(403,'Private session grant required. Rejoin this client.');m.lastSeen=now();return m}
function leave(r,m){if(!r.members.delete(m.id))return;tv.drop(r,m.id);native.closeMember(r.slug,m.id);for(const[ws,a]of audio)if(a.room===r.slug&&a.clientId===m.id){audio.delete(ws);ws.close(1000,'Room left')}const poll=r.polls.get(m.id);if(poll){clearTimeout(poll.timer);r.polls.delete(m.id);json(poll.res,401,{error:'Room session ended.'})}if(r.hostId===m.id){r.hostId=r.members.keys().next().value||null;emit(r,'host_state',{hostId:r.hostId})}emit(r,'member_left',{name:m.name,members:list(r),hostId:r.hostId});rosterChanged(r.slug)}
function mediaURL(value){if(value==='/media/orbit.mp4')return value;let u;try{u=new URL(value)}catch{throw problem(400,'Use a direct HTTPS video URL, not a streaming-service page.')}if(/(^|\.)(netflix\.com|hulu\.com|paramountplus\.com|disneyplus\.com|max\.com|peacocktv\.com|primevideo\.com)$/.test(u.hostname))throw problem(400,'That is a streaming-service page, not a direct video. Keep it in the official app; use the separate experimental TV connector for device testing.');if(u.protocol!=='https:'||u.hostname.startsWith('[')||u.username||u.password||(u.hostname==='localhost'||u.hostname.endsWith('.localhost'))||!/[a-z]/i.test(u.hostname)||/\.(local|internal)$/.test(u.hostname))throw problem(400,'Use a public HTTPS video URL.');return u.href}
function command(r,m,p){if(!p||typeof p.type!=='string')throw problem(400,'Invalid room action.');rate('member:'+m.id,180,10000);m.lastSeen=now();const reqId=text(p.reqId,24);if(reqId&&m.acks.has(reqId))return m.acks.get(reqId);let result;
 if(p.type==='ping'||p.type==='stats'){result={seq:r.seq};}
 else if(p.type==='host_claim'){if(r.hostId&&r.hostId!==m.id&&p.takeover!==true)throw problem(409,'Another person is hosting.');r.hostId=m.id;result=emit(r,'host_state',{hostId:m.id,from:m.id});}
 else if(p.type==='host_release'){if(r.hostId!==m.id)throw problem(403,'Only the host can release control.');r.hostId=[...r.members.keys()].find(x=>x!==m.id)||null;result=emit(r,'host_state',{hostId:r.hostId});}
 else if(p.type==='chat'){const s=text(p.text,280);if(!s)throw problem(400,'Write a message first.');result=emit(r,'chat',{from:m.id,name:m.name,text:s});}
 else if(p.type==='moment'){const positionSec=Number(p.positionSec);if(!Number.isFinite(positionSec)||positionSec<0)throw problem(400,'Invalid moment.');const mark={id:id(),positionSec,label:text(p.label,60)||'Saved moment',by:m.name};r.moments.push(mark);if(r.moments.length>50)r.moments.shift();result=emit(r,'moment',mark);}
 else if(p.type.startsWith('tv_')){result=tv.handle(r,m,p);}
 else if(p.type==='sync'){
  if(r.hostId!==m.id)throw problem(403,'Only the host changes playback.');
  const sameMedia=p.mediaUrl===undefined||p.mediaUrl===r.sync.mediaUrl;
  const pos=Number(p.positionSec),duration=Number(p.runtimeSec!==undefined?p.runtimeSec:(sameMedia?r.sync.runtimeSec:0));if(!Number.isFinite(pos)||pos<0||pos>172800||!Number.isFinite(duration)||duration<0||duration>172800)throw problem(400,'Invalid playback time.');
  const mode=p.mode==='external'?'external':'native';if(r.tvPlan&&(mode!=='external'||r.sync.provider!==p.provider||r.sync.contentKey!==p.contentKey))tv.invalidate(r,'The room changed content. Confirm the new episode before aligning.');if(!['live','paused','seeking','idle'].includes(p.status))throw problem(400,'Invalid playback state.');
  let serverTime=now();if(p.sampledAt!==undefined){if(!Number.isFinite(p.sampledAt)||p.sampledAt<serverTime-10000||p.sampledAt>serverTime+1000)throw problem(400,'Playback clock needs resynchronizing.');serverTime=Math.min(serverTime,p.sampledAt)}
  const s={mode,status:p.status,positionSec:pos,runtimeSec:duration,mediaUrl:mode==='native'?mediaURL(p.mediaUrl||r.sync.mediaUrl):'',mediaTitle:text(p.mediaTitle,120)||r.sync.mediaTitle,format:p.format==='hls'?'hls':'mp4',serverTime,from:m.id,provider:text(p.provider,30),contentKey:text(p.contentKey,120),hold:!!p.hold};
  r.sync={...s,v:2,type:'sync',room:r.slug,seq:r.seq+1,ts:now()};result=emit(r,'sync',s);r.sync={...result};
 }else throw problem(400,'Unknown room action.');
 const ack={type:'ack',ok:true,reqId,seq:result.seq,ts:now(),hostId:r.hostId};if(reqId){m.acks.set(reqId,ack);if(m.acks.size>100)m.acks.delete(m.acks.keys().next().value)}return ack;
}
async function serveFile(req,res,file,type){let stat;try{stat=await fs.promises.stat(file)}catch{throw problem(404,'File not found.')}headers(res);res.setHeader('Cache-Control',type.includes('html')?'no-cache':'public, max-age=3600');res.setHeader('Content-Type',type);let start=0,end=stat.size-1,status=200;const range=req.headers.range;if(range){const a=/^bytes=(\d+)-(\d*)$/.exec(range);if(!a)throw problem(416,'Unsupported range.');start=Number(a[1]);end=a[2]?Math.min(Number(a[2]),end):end;if(start>end||start>=stat.size)throw problem(416,'Invalid range.');status=206;res.setHeader('Content-Range',`bytes ${start}-${end}/${stat.size}`)}res.setHeader('Accept-Ranges','bytes');res.setHeader('Content-Length',end-start+1);res.writeHead(status);if(req.method==='HEAD')return res.end();const stream=fs.createReadStream(file,{start,end});stream.on('error',()=>res.destroy());res.on('close',()=>stream.destroy());stream.pipe(res)}
const server=http.createServer(async(req,res)=>{try{
 const u=new URL(req.url,'http://local'),p=u.pathname;if(!originOK(req))throw problem(403,'Open Showcials directly to continue.');
 applyRequestBudget(req,u,rooms,equal,rate,ip(req));
 if((req.method==='GET'||req.method==='HEAD')&&p==='/api/health')return json(res,200,{ok:true,app:'Showcials Orbit',version:'11.3.0',capabilities:{tvConnector:true,atomicEndOfTalk:true,nativeMemberBudgets:true},rooms:rooms.size,ts:now()});
 if(req.method==='POST'&&p==='/api/rooms/new'){await body(req);rate('new:'+ip(req),8,3600000);return json(res,201,{room:createRoom().slug})}
 if(req.method==='GET'&&p==='/api/catalog')return json(res,200,[]);
 if(req.method==='GET'&&(p==='/api/rooms'||p==='/api/guilds'))return json(res,200,[]);
 const a=/^\/api\/rooms\/([a-zA-Z0-9-]+)\/(join|poll|event|leave|moments|voice\/(?:open|push|pull|close))$/.exec(p);
 if(a){const r=getRoom(a[1]),action=a[2];if(req.method==='POST'&&action==='join'){rate('join:'+ip(req),30,60000);const b=await body(req),m=join(r,b.name,b.kind);return json(res,200,welcome(r,m))}
  const b=req.method==='POST'?await body(req):{};let m;if(action.startsWith('voice/')&&action!=='voice/open'){m=r.members.get(b.clientId);if(!m)throw problem(401,'Room session expired.');native.session(r.slug,m,b);m.lastSeen=now()}else m=member(r,b.clientId||u.searchParams.get('clientId'),req.headers['x-session-grant']||b.nativeVoiceGrant);
  if(req.method==='GET'&&action==='poll'){const since=Math.max(0,Number(u.searchParams.get('since'))||0);const old=r.polls.get(m.id);if(old){clearTimeout(old.timer);r.polls.delete(m.id);json(old.res,200,snapshot(r,old.since))}if(since<r.seq||u.searchParams.get('epoch')!==r.epoch)return json(res,200,snapshot(r,since));const poll={res,since,timer:setTimeout(()=>{if(r.polls.get(m.id)===poll){r.polls.delete(m.id);json(res,200,snapshot(r,since))}},20000)};r.polls.set(m.id,poll);res.on('close',()=>{if(r.polls.get(m.id)===poll){clearTimeout(poll.timer);r.polls.delete(m.id)}});return}
  if(req.method==='POST'&&action==='event'){const ack=command(r,m,b);return json(res,200,{ok:true,ack,ts:ack.ts})}
  if(req.method==='POST'&&action==='leave'){leave(r,m);return json(res,200,{ok:true})}
  if(req.method==='GET'&&action==='moments')return json(res,200,{moments:r.moments});
  if(req.method==='POST'&&action.startsWith('voice/')){let v;if(action==='voice/open')v=native.open(r.slug,m,b,voiceList(r).length);else{const session=native.session(r.slug,m,b);if(action==='voice/push')v=native.push(session,b);if(action==='voice/pull')v=native.pull(session);if(action==='voice/close'){native.closeMember(r.slug,m.id);v={ok:true}}}return json(res,200,v)}
  throw problem(405,'Method not allowed.');
 }
 if(req.method==='GET'||req.method==='HEAD'){
  const table={'/':['index.html','text/html; charset=utf-8'],'/preview':['index.html','text/html; charset=utf-8'],'/hls.min.js':['hls.min.js','text/javascript; charset=utf-8'],'/app.js':['app.js','text/javascript; charset=utf-8'],'/style.css':['style.css','text/css; charset=utf-8'],'/capture-worklet.js':['capture-worklet.js','text/javascript; charset=utf-8'],'/media/orbit.mp4':['orbit.mp4','video/mp4'],'/media/orbit.webm':['orbit.webm','video/webm'],'/compat.js':['compat.js','text/javascript; charset=utf-8'],'/tv.js':['tv.js','text/javascript; charset=utf-8'],'/roku-connector.py':['roku-connector.py','text/x-python; charset=utf-8'],'/favicon.svg':['favicon.svg','image/svg+xml']};
  if(table[p])return await serveFile(req,res,path.join(ROOT,'web',table[p][0]),table[p][1]);
 }
 throw problem(404,'Not found.');
}catch(e){if(!res.headersSent)json(res,e.status||500,{error:e.status?e.message:'Server error. Please try again.'});else res.destroy();if(!e.status)console.error('Request failed:',e.code||e.name)}});
server.requestTimeout=30000;server.headersTimeout=10000;
server.on('upgrade',(req,socket,head)=>{try{rate('upgrade:'+ip(req),40,60000);if(!originOK(req))throw problem(403,'Origin rejected');const u=new URL(req.url,'http://local'),r=getRoom(u.searchParams.get('room'));if(u.pathname==='/ws'){if(r.members.size>=12)throw problem(409,'Room full');wss.handleUpgrade(req,socket,head,ws=>wss.emit('connection',ws,req,r,u))}else if(u.pathname==='/voice'){const m=member(r,u.searchParams.get('clientId'),u.searchParams.get('grant')||u.searchParams.get('nativeVoiceGrant'));if(voiceList(r).length>=12)throw problem(409,'Voice full');vss.handleUpgrade(req,socket,head,ws=>vss.emit('connection',ws,req,r,m))}else throw problem(404,'Not found')}catch(e){socket.end(`HTTP/1.1 ${e.status||400} Rejected\r\nConnection: close\r\nContent-Length: 0\r\n\r\n`)}});
wss.on('connection',(ws,req,r,u)=>{let m;try{m=join(r,u.searchParams.get('name'),'browser',ws)}catch{ws.close();return}send(ws,welcome(r,m));ws.on('error',()=>{});ws.on('message',(data,binary)=>{let packet;try{if(binary)throw problem(400,'Use voice channel for audio.');const p=packet=JSON.parse(data.toString());if(!p||typeof p!=='object'||Array.isArray(p)||typeof p.type!=='string')throw problem(400,'Invalid packet.');send(ws,command(r,m,p))}catch(e){send(ws,{type:'error',reqId:text(packet?.reqId,24),error:e.status?e.message:'Invalid room message.'})}});ws.on('close',()=>leave(r,m));});
vss.on('connection',(ws,req,r,m)=>{for(const[old,a]of audio)if(a.clientId===m.id){audio.delete(old);old.close()}const a={id:id(),room:r.slug,clientId:m.id,name:m.name,muted:true,lastSeen:now()};audio.set(ws,a);send(ws,{type:'voice_welcome',id:a.id});rosterChanged(r.slug);ws.on('error',()=>{});ws.on('pong',()=>{a.lastSeen=now();m.lastSeen=now()});ws.on('message',(data,binary)=>{try{a.lastSeen=now();m.lastSeen=now();if(binary){rate('audio:'+a.id,75,1000);if(data.length!==640)throw problem(400,'Invalid audio frame.');if(a.muted){a.muted=false;rosterChanged(r.slug)}native.accept(r.slug,a.id,m.id,data);for(const[other,peer]of audio)if(other!==ws&&peer.room===r.slug&&other.bufferedAmount<64000){send(other,{type:'voice_frame',from:a.id});send(other,data,true)}}else{const p=JSON.parse(data.toString());if(p.type==='voice_state'){a.muted=p.muted!==false;rosterChanged(r.slug)}}}catch{ws.close(1008,'Invalid voice data')}});ws.on('close',()=>{audio.delete(ws);rosterChanged(r.slug)})});
const timer=setInterval(()=>{const t=now();native.sweep();for(const[k,a]of rates)if(t>a.until)rates.delete(k);for(const[ws,a]of audio){if(t-a.lastSeen>40000)ws.terminate();else ws.ping()}for(const r of rooms.values()){tv.tick(r);for(const m of r.members.values())if(t-m.lastSeen>90000){if(m.ws)m.ws.terminate();leave(r,m)}if(!r.members.size&&t-r.lastActive>3600000)rooms.delete(r.slug)}},15000);timer.unref();
function shutdown(){clearInterval(timer);for(const r of rooms.values())for(const m of [...r.members.values()]){if(m.ws)m.ws.close(1001,'Server restarting');leave(r,m)}native.clear();server.close(()=>process.exit(0));setTimeout(()=>process.exit(0),2000).unref()}
process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
server.listen(PORT,process.env.HOST||'0.0.0.0',()=>console.log(`Showcials Orbit listening on ${PORT}`));
