'use strict';
const assert=require('node:assert/strict');let WS;try{WS=require('ws').WebSocket}catch{WS=require('../showcials-roku-native-v10.1/vendor/ws.cjs').WebSocket}
const base=process.env.BASE_URL||'http://127.0.0.1:7801';let n=0;const pass=s=>{console.log('PASS',++n,s)};
async function req(p,b,grant){const r=await fetch(base+p,{method:b===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(grant?{'X-Session-Grant':grant}:{})},body:b===undefined?undefined:JSON.stringify(b)});return {status:r.status,data:await r.json()}}
function client(path){return new Promise((resolve,reject)=>{const ws=new WS(base.replace(/^http/,'ws')+path),packets=[],waits=[];ws.binaryType='nodebuffer';ws.on('message',(x,b)=>{const p=b?x:JSON.parse(x.toString());packets.push(p);for(const w of [...waits])if(w.fn(p)){clearTimeout(w.timer);waits.splice(waits.indexOf(w),1);w.ok(p)}});ws.on('error',reject);ws.on('open',()=>resolve({ws,packets,next(fn){const p=packets.find(fn);if(p)return Promise.resolve(p);return new Promise((ok,no)=>{const w={fn,ok,timer:setTimeout(()=>no(Error('Packet timeout')),4000)};waits.push(w)})}}))})}
(async()=>{const r=await req('/api/rooms/new',{});assert.equal(r.status,201);const room=r.data.room;assert.match(room,/^[a-z0-9]{8}$/);pass('server creates unlisted room');
const a=await client('/ws?room='+room+'&name=Host'),welcome=await a.next(x=>x.type==='welcome');const b=await req('/api/rooms/'+room+'/join',{name:'Roku test client',kind:'roku'}),m=b.data;assert.equal(b.status,200);assert(m.nativeVoiceGrant);pass('browser WebSocket and native REST join share room');
a.ws.send(JSON.stringify({type:'sync',reqId:'s1',positionSec:5,status:'live',runtimeSec:24,mediaUrl:'/media/orbit.mp4',mediaTitle:'Orbit',mode:'native',sampledAt:Date.now()-200}));const ack=await a.next(x=>x.type==='ack'&&x.reqId==='s1');assert(ack.ok);pass('host sync is acknowledged');
const poll=await req('/api/rooms/'+room+'/poll?clientId='+m.clientId+'&since=0',undefined,m.nativeVoiceGrant);assert.equal(poll.data.sync.positionSec,5);assert.equal(poll.data.sync.status,'live');pass('Roku protocol receives complete authoritative timeline');
let x=await req('/api/rooms/'+room+'/event',{clientId:m.clientId,type:'sync',positionSec:20,status:'paused',mediaUrl:'/media/orbit.mp4'},m.nativeVoiceGrant);assert.equal(x.status,403);pass('follower cannot overwrite host');
x=await req('/api/rooms/'+room+'/event',{clientId:m.clientId,type:'chat',text:'<script>not executable</script>',reqId:'c1'},m.nativeVoiceGrant);assert.equal(x.status,200);const chat=await a.next(x=>x.type==='chat'&&x.text.includes('not executable'));assert.equal(chat.name,'Roku test client');pass('native protocol chat reaches real browser socket');
x=await req('/api/rooms/'+room+'/event',{clientId:m.clientId,type:'chat',text:'forged'},'wrong');assert.equal(x.status,403);pass('private member grant prevents impersonation');
const v=await req('/api/rooms/'+room+'/voice/open',{clientId:m.clientId,nativeVoiceGrant:m.nativeVoiceGrant,adultNonChildSession:true});assert.equal(v.status,200);const browserVoice=await client('/voice?room='+room+'&clientId='+welcome.clientId+'&grant='+welcome.nativeVoiceGrant);const frame=Buffer.alloc(640);frame.writeInt16LE(1000,0);x=await req('/api/rooms/'+room+'/voice/push',{clientId:m.clientId,voiceId:v.data.voiceId,voiceSecret:v.data.voiceSecret,seq:1,pcm:frame.toString('base64'),format:'pcm-s16-le',sampleRate:16000,channels:1,muted:false});assert.equal(x.status,200);const heard=await browserVoice.next(x=>Buffer.isBuffer(x));assert(heard.equals(frame));pass('native voice PCM reaches browser transport unchanged');
browserVoice.ws.send(frame);await new Promise(r=>setTimeout(r,80));x=await req('/api/rooms/'+room+'/voice/pull',{clientId:m.clientId,voiceId:v.data.voiceId,voiceSecret:v.data.voiceSecret});assert.equal(x.status,200);const wav=Buffer.from(x.data.wav,'base64');assert.equal(wav.subarray(0,4).toString(),'RIFF');pass('browser voice reaches native WAV return transport');
const media=await fetch(base+'/media/orbit.mp4',{headers:{Range:'bytes=0-99'}});assert.equal(media.status,206);assert.equal((await media.arrayBuffer()).byteLength,100);pass('original movie supports byte-range decoding');
x=await req('/api/rooms/'+room+'/event',{clientId:m.clientId,type:'host_claim',takeover:true,reqId:'take'},m.nativeVoiceGrant);assert.equal(x.status,200);pass('explicit native host takeover');
a.ws.send(JSON.stringify({type:'sync',reqId:'denied',positionSec:8,status:'paused',mediaUrl:'/media/orbit.mp4'}));await a.next(x=>x.type==='error');pass('former host is rejected');
x=await req('/api/rooms/'+room+'/voice/push',{clientId:m.clientId,voiceId:v.data.voiceId,voiceSecret:'bad',seq:2,pcm:''});assert.equal(x.status,401);pass('native voice secret required for subsequent pushes');
assert.equal((await fetch(base+'/api/health',{headers:{Origin:'https://other.invalid'}})).status,403);pass('foreign browser origin rejected');
assert.equal((await req('/api/rooms')).data.length,0);pass('room codes are not publicly listed');
browserVoice.ws.close();a.ws.close();await req('/api/rooms/'+room+'/leave',{clientId:m.clientId},m.nativeVoiceGrant);console.log(n+' protocol checks passed. Roku clients are simulated REST clients; not hardware.');setTimeout(()=>process.exit(0),100);
})().catch(e=>{console.error(e);process.exit(1)});
