'use strict';
const assert=require('node:assert/strict');const {TVSession}=require('../lib/tv-session');
let time=100000,seq=0,events=[];const room={slug:'testroom',members:new Map(),hostId:'host',sync:{mode:'external',provider:'netflix',contentKey:'episode1',status:'paused'}};
for(const id of ['host','guest','a','b'])room.members.set(id,{id,name:id});
const tv=new TVSession({now:()=>time,emit:(r,type,p)=>{const e={type,...p,ts:time,seq:++seq};events.push(e);return e;}});
const call=(id,p)=>tv.handle(room,room.members.get(id),p);let count=0;
const test=(name,fn)=>{fn();console.log('PASS',++count,name)};
test('registration requires explicit local consent',()=>assert.throws(()=>call('a',{type:'tv_register',ownerId:'host',provider:'netflix'}),/consent/));
for(const[id,owner]of[['a','host'],['b','guest']])call(id,{type:'tv_register',ownerId:owner,provider:'netflix',consent:true});
test('guest cannot launch host-owned TV',()=>assert.throws(()=>call('guest',{type:'tv_action',target:'a',action:'launch'}),/paired/));
test('host cannot launch guest-owned TV',()=>assert.throws(()=>call('host',{type:'tv_action',target:'b',action:'launch'}),/paired/));
test('owning browser can request installed app launch',()=>{call('guest',{type:'tv_action',target:'b',action:'launch'});assert.equal(events.at(-1).target,'b')});
test('unknown timestamps block alignment',()=>assert.throws(()=>call('host',{type:'tv_action',action:'align'}),/recent timestamp/));
function ready(id,pos){call(id,{type:'tv_status',state:'playing',armed:true,canRead:true,positionSec:pos,observedAt:time,contentKey:'episode1'})}
ready('a',12);ready('b',8);
test('follower cannot align all TVs',()=>assert.throws(()=>call('guest',{type:'tv_action',action:'align'}),/host/));
test('alignment first requests pause on both devices',()=>{call('host',{type:'tv_action',action:'align'});assert.equal(room.tvPlan.phase,'pausing');assert.equal(events.filter(e=>e.type==='tv_command'&&e.op==='pause').length,2)});
const aid=room.tvPlan.id;
test('unrelated member cannot forge a paused device result',()=>assert.throws(()=>call('guest',{type:'tv_result',alignmentId:aid,ok:true,state:'paused',positionSec:9,op:'pause'}),/Unknown TV/));
call('a',{type:'tv_result',alignmentId:aid,ok:true,state:'paused',positionSec:12,op:'pause'});
test('one paused response does not prematurely start either TV',()=>assert.equal(room.tvPlan.phase,'pausing'));
call('b',{type:'tv_result',alignmentId:aid,ok:true,state:'paused',positionSec:8,op:'pause'});
test('trailing TV starts exactly four seconds earlier without seeking',()=>{const a=events.find(e=>e.op==='play_at'&&e.target==='a'),b=events.find(e=>e.op==='play_at'&&e.target==='b');assert.equal(a.startAt-b.startAt,4000);assert.equal(b.startAt,time+4000);assert.equal(room.sync.positionSec,8)});
test('missing playback confirmations never claim running',()=>assert.equal(room.tvPlan.phase,'scheduled'));
call('b',{type:'tv_result',alignmentId:aid,ok:true,state:'playing',op:'play_at'});call('a',{type:'tv_result',alignmentId:aid,ok:true,state:'playing',op:'play_at'});
test('both playback readbacks complete the start plan',()=>assert.equal(room.tvPlan.phase,'running'));
test('loss of readable timestamp cancels remaining control',()=>{call('b',{type:'tv_status',state:'unavailable',positionSec:null,armed:false,canRead:false,observedAt:time});assert.equal(room.tvPlan.phase,'stopped')});
ready('a',12);ready('b',8);call('host',{type:'tv_action',action:'align'});
test('timeout cancels plan rather than claiming synchronization',()=>{time+=11000;tv.tick(room);assert.equal(room.tvPlan.phase,'stopped')});
ready('a',100);ready('b',2);call('host',{type:'tv_action',action:'align'});
const long=room.tvPlan.id;for(const[id,pos]of[['a',100],['b',2]])call(id,{type:'tv_result',alignmentId:long,ok:true,state:'paused',positionSec:pos,op:'pause'});
test('large gaps request a common scene instead of FF or seek',()=>{assert.equal(room.tvPlan.phase,'stopped');assert.match(room.tvPlan.message,/30 seconds/)});
test('room snapshots contain no IPs, grants, credentials or private URLs',()=>{assert(!/password|grant|192\.168|secret/.test(JSON.stringify(tv.state(room))))});
test('withdrawal removes device and clears active plan',()=>{tv.drop(room,'b');assert.equal(tv.public(room).length,1)});
console.log(count+' coordinator checks passed (simulated device observations; not physical Roku).');
