'use strict';
const $=id=>document.getElementById(id);
const S={room:'',id:'',hostId:'',grant:'',ws:null,voice:null,preview:false,seq:0,members:[],sync:null,clock:null,pending:new Map(),generation:0,mediaGeneration:0,suppressUntil:0,rxFrames:0,txFrames:0,lastPublished:0,volume:.7};
window.SC=S;
let pref={large:false,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,contrast:false,music:false,volume:.18};
try{Object.assign(pref,JSON.parse(localStorage.getItem('showcials.preferences')||'{}'))}catch{}
let name='';try{name=sessionStorage.getItem('showcials.name')||''}catch{}
let toastTimer,focusBefore,selected=0,raf=0,publishTimer,reconnectTimer,heartbeat,watchdog,animation;
const channels=[{kind:'start',title:'Your cinema',subtitle:'Start something together',action:'Start a room',tag:'01 / WATCH TOGETHER'}, {kind:'join',title:'Your people',subtitle:'A room is waiting for you',action:'Join a room',tag:'02 / BETTER TOGETHER'}, {kind:'preview',title:'Take a look',subtitle:'Step inside. No setup.',action:'Play the preview',tag:'03 / YOUR FIRST ORBIT'}, {kind:'services',title:'Your services',subtitle:'Netflix · Hulu · and more',action:'See how it works',tag:'04 / OPEN SEPARATELY'}, {kind:'roku',title:'On your TV',subtitle:'The Showcials Roku project',action:'Roku information',tag:'05 / NATIVE APP PROJECT'}, {kind:'calm',title:'A little calm',subtitle:'Make yourself comfortable',action:'Sound & accessibility',tag:'06 / SETTLE IN'}];
function notify(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6500)}
function savePrefs(){document.body.classList.toggle('reduced',pref.reduced);document.body.classList.toggle('contrast',pref.contrast);document.body.classList.toggle('large',pref.large);document.documentElement.style.setProperty('--scale',pref.large?'1.18':'1');try{localStorage.setItem('showcials.preferences',JSON.stringify(pref))}catch{}}
function el(tag,cls,content){const n=document.createElement(tag);if(cls)n.className=cls;if(content!==undefined)n.textContent=content;return n}
function modal(title){focusBefore=document.activeElement;$('dialogTitle').textContent=title;$('dialogContent').replaceChildren();if(!$('dialog').open)$('dialog').showModal();return $('dialogContent')}
function closeModal(){$('dialog').close();if(focusBefore&&focusBefore.isConnected)focusBefore.focus()}
$('closeDialog').onclick=closeModal;$('dialog').addEventListener('cancel',()=>{if(focusBefore?.isConnected)focusBefore.focus()});
function paragraph(root,value,cls){root.append(el('p',cls,value))}
function button(root,label,fn,cls='primary'){const b=el('button',cls,label);b.type='button';b.onclick=fn;root.append(b);return b}
function field(root,label,placeholder,value=''){const id='field-'+Math.random().toString(36).slice(2);const l=el('label','',label);l.htmlFor=id;const input=el('input');input.id=id;input.placeholder=placeholder;input.value=value;root.append(l,input);return input}
function showSettings(){const c=modal('Make yourself comfortable.');paragraph(c,'The same beautiful cinema, at your pace.');for(const[key,label]of[['large','Larger text'],['reduced','Less motion · flatter channel cards'],['contrast','Stronger contrast']]){const l=el('label','setting',label),i=el('input');i.type='checkbox';i.checked=pref[key];i.onchange=()=>{pref[key]=i.checked;savePrefs();updateGallery()};l.append(i);c.append(l)}const l=el('label','setting','Menu music volume'),i=el('input');i.type='range';i.min=0;i.max=.35;i.step=.01;i.value=pref.volume;i.setAttribute('aria-label','Menu music volume');i.oninput=()=>{pref.volume=Number(i.value);savePrefs();duckMusic()};l.append(i);c.append(l);button(c,musicOn?'Turn menu music off':'Turn menu music on',async()=>{await toggleMusic();showSettings()},'secondary');paragraph(c,'Original ambient music and soft selection tones. Music stays quiet while a video plays or your microphone is on.','fine')}
function showHelp(){const c=modal('A good night, in three steps.');const steps=el('div','steps');for(const t of ['1. Start a room. Pick a display name and we do the rest.','2. Invite your people. Copy the room link and send it to them.','3. Press Play. The host controls the film; everyone can type or join voice.'])paragraph(steps,t);c.append(steps);paragraph(c,'Need something bigger or calmer? Open Settings for larger text, stronger contrast, and less motion.');button(c,'Open accessibility settings',showSettings,'secondary');paragraph(c,'This release plays the original sample and compatible authorized direct videos. Netflix and Hulu are not built into this player.','fine')}
function showPrivacy(){const c=modal('You are in control.');paragraph(c,'No advertising analytics. No app-recorded voice. Your microphone is off until you choose Talk together and grant permission.');paragraph(c,'Names, chat, and playback state are processed by the room server. Voice passes through the server; it is not end-to-end encrypted. Room data is held temporarily in memory and is lost on a server restart. Empty rooms expire after an hour.');paragraph(c,'Anyone with a room code or invite link can enter. Only share them with people you trust. Hosting providers may keep connection metadata such as IP addresses. Others can record what they hear.');paragraph(c,'The voice demonstration is for consenting adults in sessions not directed to children. Never enter account passwords or payment information here.','fine')}
function showServices(){if(window.ShowcialsTV)return window.ShowcialsTV.open();const c=modal('Your subscriptions stay yours.');paragraph(c,'Netflix, Hulu, and other subscription services open in their own official players. This website does not unlock, embed, or rebroadcast their films.');const l=el('div','service-list');for(const[label,url]of[['Netflix','https://www.netflix.com/'],['Hulu','https://www.hulu.com/'],['Disney+','https://www.disneyplus.com/'],['Prime Video','https://www.primevideo.com/']]){const a=el('a','',label+' ↗');a.href=url;a.target='_blank';a.rel='noopener noreferrer';l.append(a)}c.append(l);paragraph(c,'Automatic subscription-player control is not verified in this web release. The separate project includes experimental browser-extension adapters. For a dependable demonstration here, use the built-in original video or an authorized direct video.');button(c,'Try the working video preview',()=>{closeModal();previewRoom()})}
function showRoku(){if(window.ShowcialsTV)return window.ShowcialsTV.open();const c=modal('Showcials on Roku.');paragraph(c,'The separate native Roku package has its own video player, room chat, and experimental hold-OK remote voice. It requires installation on a Roku you control. This website cannot install an app on your TV by itself.');paragraph(c,'To connect the existing native package to this web edition, use this server address and the same room code. The web edition does not require a relay access key.');const a=field(c,'Server address','',(window.ORBIT_OFFLINE||location.protocol==='file:')?'Start the included server first':location.origin);a.readOnly=true;if(S.room){const b=field(c,'Room code','',S.room.toUpperCase());b.readOnly=true}paragraph(c,'Protocol compatibility is tested separately from hardware. Physical Roku playback, remote microphone capture, and Netflix/Hulu native-app synchronization are not verified. Native voice is not a background overlay over another Roku app.','fine')}
channels.forEach((ch,index)=>{const b=el('button','channel');b.dataset.kind=ch.kind;b.setAttribute('aria-label',ch.action);const cover=el('div','cover'),spine=el('div','spine','SHOWCIALS / '+String(index+1).padStart(2,'0')),face=el('div','face'),tag=el('div','case-tag',ch.tag),art=el('div','art');art.append(el('div','planet'),el('div','ring'),el('div','ring r2'));const t=el('div','case-text');t.append(el('strong','',ch.title),el('small','',ch.subtitle),el('span','case-action',ch.action+' ↗'));face.append(tag,art,t);cover.append(spine,face);b.append(cover);b.onclick=()=>{tone();({start:showStart,join:showJoin,preview:previewRoom,services:showServices,roku:showRoku,calm:showSettings}[ch.kind])()};b.onfocus=()=>scrollChannel(index);$('gallery').append(b);const dot=el('button');dot.setAttribute('aria-label','Show '+ch.title);dot.onclick=()=>scrollChannel(index);$('channelDots').append(dot)});
function scrollChannel(index){index=Math.max(0,Math.min(channels.length-1,index));const b=$('gallery').children[index];$('gallery').scrollTo({left:b.offsetLeft-($('gallery').clientWidth-b.offsetWidth)/2,behavior:pref.reduced?'instant':'smooth'})}
function updateGallery(){raf=0;const g=$('gallery'),middle=g.scrollLeft+g.clientWidth/2;let nearest=0,min=1e9;[...g.children].forEach((b,i)=>{const distance=b.offsetLeft+b.offsetWidth/2-middle;if(Math.abs(distance)<min){min=Math.abs(distance);nearest=i}const d=Math.max(-1.7,Math.min(1.7,distance/310));b.querySelector('.cover').style.setProperty('--angle',(-d*32)+'deg');b.querySelector('.cover').style.setProperty('--depth',(-Math.abs(d)*45)+'px');b.style.filter='brightness('+(1-Math.min(.25,Math.abs(d)*.13))+')'});selected=nearest;[...g.children].forEach((b,i)=>b.classList.toggle('selected',i===nearest));[...$('channelDots').children].forEach((b,i)=>b.setAttribute('aria-current',String(i===nearest)));$('previous').disabled=selected===0;$('next').disabled=selected===channels.length-1}
$('gallery').addEventListener('scroll',()=>{if(!raf)raf=requestAnimationFrame(updateGallery)},{passive:true});let wheel=0;$('gallery').addEventListener('wheel',e=>{if(Math.abs(e.deltaX)>Math.abs(e.deltaY))return;if((selected===0&&e.deltaY<0)||(selected===channels.length-1&&e.deltaY>0))return;e.preventDefault();if(performance.now()-wheel<300)return;wheel=performance.now();scrollChannel(selected+(e.deltaY>0?1:-1));tone()},{passive:false});$('gallery').addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const n=Math.max(0,Math.min(channels.length-1,selected+(e.key==='ArrowRight'?1:-1)));$('gallery').children[n].focus()}});$('previous').onclick=()=>{scrollChannel(selected-1);tone()};$('next').onclick=()=>{scrollChannel(selected+1);tone()};window.addEventListener('resize',()=>{updateGallery();scrollChannel(selected)});
async function request(p,data){const r=await fetch(p,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const b=await r.json();if(!r.ok)throw Error(b.error||'Please try again.');return b}
function rememberName(value){name=value.trim().slice(0,32)||'Guest';try{sessionStorage.setItem('showcials.name',name)}catch{}}
function showStart(){const c=modal('Who is joining us?');paragraph(c,'Pick a name your friends will recognize. No account needed.');const n=field(c,'Your display name','Your first name',name);n.maxLength=32;n.autocomplete='given-name';const b=button(c,'Start my room',async()=>{if((window.ORBIT_OFFLINE||location.protocol==='file:'))return notify('This file is a local preview. Open the hosted website for a shared room.');b.disabled=true;b.textContent='Opening your room…';try{rememberName(n.value);const r=await request('/api/rooms/new',{});closeModal();await enterRoom(r.room)}catch(e){notify(e.message);b.disabled=false;b.textContent='Start my room'}});n.onkeydown=e=>{if(e.key==='Enter')b.click()};setTimeout(()=>n.focus(),80)}
function extractRoom(value){try{const u=new URL(value);return new URLSearchParams(u.hash.slice(1)).get('room')||''}catch{return value.toLowerCase().replace(/[^a-z0-9]/g,'')}}
function showJoin(preset=''){const c=modal('Your people are waiting.');paragraph(c,'Paste their invite link, or enter the eight-character room code.');const code=field(c,'Room code or invite link','Example: ABCD EFGH',preset);code.autocomplete='off';const n=field(c,'Your display name','Your first name',name);n.maxLength=32;const b=button(c,'Join the room',()=>{const r=extractRoom(code.value);if(!/^[a-z0-9]{8}$/.test(r))return notify('Enter the eight-character room code from your invitation.');if((window.ORBIT_OFFLINE||location.protocol==='file:'))return notify('Open the hosted website to join a room.');rememberName(n.value);closeModal();enterRoom(r)});code.onkeydown=e=>{if(e.key==='Enter')b.click()};setTimeout(()=>code.focus(),80)}
function roomLayout(){ $('lobby').hidden=true;$('watchroom').hidden=false;window.scrollTo(0,0);$('messages').replaceChildren();$('moments').replaceChildren();$('enablePlayback').hidden=true;$('videoCover').hidden=false;duckMusic()}
function disconnect(){S.generation++;clearTimeout(reconnectTimer);clearTimeout(publishTimer);clearInterval(heartbeat);clearInterval(watchdog);stopVoice();if(S.ws){const old=S.ws;S.ws=null;old.close()}for(const p of S.pending.values()){clearTimeout(p.timer);p.reject(Error('Room closed.'))}S.pending.clear();$('video').pause();S.suppressUntil=performance.now()+1000;S.id='';S.grant='';S.health={}}
function previewRoom(){disconnect();S.preview=true;S.room='';S.id='preview';S.hostId='preview';S.members=[{id:'preview',name:'You · preview'}];roomLayout();$('roomTitle').textContent='Your preview cinema';$('roomKicker').textContent='TAKE A LOOK AROUND';$('peopleStatus').textContent='Local preview · no guests connected';$('invite').textContent='Start a real room ↗';$('screenBadge').textContent='LOCAL PREVIEW';$('talk').disabled=true;$('voiceStatus').textContent='Voice is available in a connected room.';addMessage('Showcials','This is a local preview. Video controls and notes work here. Start a room to invite real people.',true);applySync({...demoSync(),from:''},true);renderPeople();watchdog=setInterval(tick,500)}
function demoSync(){return {mode:'native',mediaUrl:window.ORBIT_DEMO||'/media/orbit.mp4',mediaTitle:'Orbit — a Showcials original',positionSec:0,runtimeSec:24,status:'paused',serverTime:Date.now()}}
async function enterRoom(code){disconnect();S.preview=false;S.room=code;S.clock=null;S.sync=null;S.members=[];roomLayout();$('talk').disabled=true;$('invite').textContent='Invite someone ↗';$('roomTitle').textContent='Your watch room';$('roomKicker').textContent='ROOM '+code.toUpperCase();$('screenBadge').textContent='SHOWCIALS ORIGINAL';history.replaceState(null,'','#room='+code);connectSocket();watchdog=setInterval(tick,500)}
function connected(){return S.ws?.readyState===WebSocket.OPEN&&!!S.id}
function connectSocket(){const gen=S.generation;const url=new URL('/ws',location.href);url.protocol=location.protocol==='https:'?'wss:':'ws:';url.searchParams.set('room',S.room);url.searchParams.set('name',name||'Guest');$('peopleStatus').textContent='Connecting to your room…';const ws=new WebSocket(url);S.ws=ws;ws.onmessage=e=>{if(gen!==S.generation||S.ws!==ws)return;let p;try{p=JSON.parse(e.data)}catch{return}if(p.type==='welcome'){window.dispatchEvent(new CustomEvent('showcials-tv',{detail:p.tv}));S.id=p.clientId;S.grant=p.nativeVoiceGrant;S.hostId=p.hostId;S.members=p.members||[];S.clock={server:p.ts,local:performance.now(),rtt:1e9,at:performance.now()};S.seq=p.since||0;$('talk').disabled=false;$('voiceStatus').textContent='Microphone is off. You’re in control.';renderPeople();applySync(p.sync,true);addMessage('Showcials','You’re connected. Invite someone and make yourself comfortable.',true);clearInterval(heartbeat);heartbeat=setInterval(reportRoomHealth,15000);reportRoomHealth();return}if(p.type==='ack'){const a=S.pending.get(p.reqId);if(a){clearTimeout(a.timer);S.pending.delete(p.reqId);const t=performance.now(),rtt=t-a.at;if(Number.isFinite(p.ts)&&rtt<5000&&(!S.clock||rtt<S.clock.rtt||t-S.clock.at>60000))S.clock={server:p.ts+rtt/2,local:t,rtt,at:t};a.resolve(p)}return}if(p.type==='error'){const pending=S.pending.get(p.reqId);if(pending){clearTimeout(pending.timer);S.pending.delete(p.reqId);pending.reject(Error(p.error||'Action rejected.'));}notify(p.error||'The room could not complete that action.');return}if(p.type==='tv_state')window.dispatchEvent(new CustomEvent('showcials-tv',{detail:p}));S.seq=Math.max(S.seq,p.seq||0);if(p.type==='stats')S.health=p.clients||{};if(p.type==='sync')applySync(p);if(p.type==='chat')addMessage(p.name,p.text);if(p.type==='member_joined'||p.type==='member_left'){S.members=p.members||S.members;if(p.hostId!==undefined)S.hostId=p.hostId;renderPeople()}if(p.type==='host_state'){S.hostId=p.hostId;renderPeople()}if(p.type==='moment')addMoment(p);if(p.type==='voice_state'&&S.voice)$('voiceStatus').textContent='Voice connected · '+(p.roster?.length||1)+' listening'};ws.onerror=()=>{};ws.onclose=()=>{if(gen!==S.generation||S.ws!==ws)return;S.id='';S.grant='';for(const p of S.pending.values()){clearTimeout(p.timer);p.reject(Error('Connection lost. Your action was not confirmed.'))}S.pending.clear();$('talk').disabled=true;stopVoice();$('peopleStatus').textContent='Room disconnected. Retrying…';$('syncStatus').textContent='Not synchronized while disconnected.';clearInterval(heartbeat);reconnectTimer=setTimeout(()=>{if(gen===S.generation){$('peopleStatus').textContent='Unable to rejoin? Check the room code or start a new room.';connectSocket()}},5000)}}
function send(type,data={}){if(!connected())return Promise.reject(Error('Join a connected room first.'));const reqId='o'+(++S.req).toString(36);const at=performance.now();return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{S.pending.delete(reqId);reject(Error('No response from the room. Check your connection.'))},9000);S.pending.set(reqId,{at,resolve,reject,timer});try{S.ws.send(JSON.stringify({v:2,type,...data,reqId}))}catch{clearTimeout(timer);S.pending.delete(reqId);reject(Error('Room disconnected.'))}})}S.req=0;
function serverNow(){return S.clock?S.clock.server+performance.now()-S.clock.local:Date.now()}
function isHost(){return S.preview||!!S.id&&S.id===S.hostId}
function renderPeople(){ $('members').replaceChildren();for(const p of S.members)$('members').append(el('span','person',p.name+(p.id===S.hostId&&!S.preview?' · host':'')));$('memberCount').textContent=String(S.members.length);if(!S.preview)$('peopleStatus').textContent=(isHost()?'You’re hosting':'Following the host')+' · '+S.members.length+' '+(S.members.length===1?'person':'people')+' in the room';$('takeControl').hidden=S.preview||isHost();for(const id of ['play','backTen','forwardTen','seek','media'])$(id).disabled=!isHost();$('invite').disabled=!S.preview&&!connected()}
function target(){if(!S.sync)return 0;let t=S.sync.positionSec||0;if(S.sync.status==='live'&&!S.sync.hold)t+=Math.max(0,(serverNow()-S.sync.serverTime)/1000);return Math.max(0,Math.min(Number.isFinite($('video').duration)?$('video').duration:t,t))}
let hls=null,currentMedia='';
function applySync(p,force=false){if(!p)return;S.sync=p;$('filmTitle').textContent=p.mediaTitle||'Shared video';if(p.mode==='external'){$('video').pause();$('videoCover').hidden=false;$('videoCover').querySelector('h2').textContent='Open your official player.';$('videoCover').querySelector('p').textContent='Subscription content is not embedded here.';return}let u=p.mediaUrl;if(!u)return;try{const parsed=new URL(u,location.href);if(!['https:','http:','data:','blob:','file:'].includes(parsed.protocol))return}catch{return}const changed=u!==currentMedia;if(changed||force){S.mediaGeneration++;const mg=S.mediaGeneration;currentMedia=u;S.suppressUntil=performance.now()+5000;if(hls){hls.destroy();hls=null}const v=$('video');v.pause();v.removeAttribute('src');if((p.format==='hls'||/\.m3u8(\?|$)/.test(u))&&window.Hls?.isSupported()&&!v.canPlayType('application/vnd.apple.mpegurl')){hls=new Hls({maxBufferLength:20});hls.loadSource(u);hls.attachMedia(v);hls.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal&&mg===S.mediaGeneration)notify('That HLS stream could not play. Try a compatible direct video.')})}else v.src=u;v.onloadedmetadata=()=>{if(mg!==S.mediaGeneration)return;S.suppressUntil=performance.now()+1200;reconcile(true)};v.load();$('videoCover').querySelector('h2').textContent='Your cinema is ready.';$('videoCover').querySelector('p').textContent='Press Play when you’re comfortable.';return}if(isHost()&&p.from===S.id&&!p.hold)return;reconcile(true)}
function reconcile(force=false){const v=$('video');if(!S.sync||S.sync.mode==='external'||v.readyState<1)return;if(!force&&performance.now()<S.suppressUntil)return;const t=target();S.suppressUntil=performance.now()+800;try{if(Math.abs(v.currentTime-t)>1.5)v.currentTime=t;if(S.sync.status==='live'&&!S.sync.hold&&v.paused)v.play().catch(()=>$('enablePlayback').hidden=false);else if((S.sync.status!=='live'||S.sync.hold)&&!v.paused)v.pause()}catch{notify('The player is not ready. Try Play again.')}}
function publish(){if(S.preview||!isHost()||!connected()||performance.now()<S.suppressUntil||!S.sync||S.sync.mode==='external')return;const v=$('video'),sample={...S.sync,positionSec:v.currentTime,status:v.paused?'paused':'live',runtimeSec:Number.isFinite(v.duration)?v.duration:S.sync.runtimeSec,sampledAt:serverNow()};delete sample.seq;delete sample.ts;delete sample.type;delete sample.from;send('sync',sample).catch(e=>notify(e.message));S.lastPublished=performance.now()}
function queuePublish(){clearTimeout(publishTimer);publishTimer=setTimeout(publish,150)}
function time(s){s=Math.max(0,Math.floor(s||0));return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')}
function tick(){const v=$('video'),d=Number.isFinite(v.duration)?v.duration:24;$('seek').max=String(d);if(document.activeElement!==$('seek'))$('seek').value=String(v.currentTime||0);$('time').textContent=time(v.currentTime)+' / '+time(d);$('play').textContent=v.paused?'▶ Play':'Ⅱ Pause';if(S.preview){$('syncStatus').textContent='Local preview · start a room to watch together';return}if(!connected())return;if(!isHost()){reconcile();const drift=Math.abs(v.currentTime-target());$('syncStatus').textContent=drift<=1.5?'Following shared playback':'Adjusting playback…'}else{$('syncStatus').textContent='You control playback for the room';if(performance.now()-S.lastPublished>2000)publish()}}
$('video').addEventListener('play',()=>{$('videoCover').hidden=true;$('enablePlayback').hidden=true;duckMusic();queuePublish()});$('video').addEventListener('pause',()=>{duckMusic();queuePublish()});$('video').addEventListener('seeked',queuePublish);$('video').addEventListener('ended',queuePublish);$('video').addEventListener('error',()=>{if(currentMedia)notify('This video could not load. Choose the original sample or another compatible video.')});
$('play').onclick=async()=>{if(!isHost())return;if(S.sync)S.sync.hold=false;S.suppressUntil=0;try{if($('video').paused)await $('video').play();else $('video').pause()}catch{notify('Tap the video playback button to allow sound.')}};
function seekBy(n){if(!isHost())return;const v=$('video');if(v.readyState<1)return;S.suppressUntil=0;v.currentTime=Math.max(0,Math.min(Number.isFinite(v.duration)?v.duration:172800,v.currentTime+n))}
$('backTen').onclick=()=>seekBy(-10);$('forwardTen').onclick=()=>seekBy(10);$('seek').onchange=()=>{if(isHost()){$('video').currentTime=Number($('seek').value);S.suppressUntil=0}};$('enablePlayback').onclick=async()=>{try{await $('video').play();$('enablePlayback').hidden=true;if(!isHost())reconcile(true)}catch{notify('Playback is still blocked by this browser.')}};$('full').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else $('screen').requestFullscreen?.().catch(()=>notify('Full screen is unavailable in this browser.'))};$('captions').onclick=()=>{$('captionBanner').hidden=!$('captionBanner').hidden;$('captions').setAttribute('aria-pressed',String(!$('captionBanner').hidden))};
function addMessage(author,message,system=false){$('messages').querySelector('.chat-empty')?.remove();const item=el('div','message'+(system?' system':''));if(!system)item.append(el('strong','',author||'Guest'));item.append(el('p','',message));$('messages').append(item);while($('messages').children.length>100)$('messages').firstChild.remove();$('messages').scrollTop=$('messages').scrollHeight}
$('chatForm').onsubmit=async e=>{e.preventDefault();const input=$('chatText'),message=input.value.trim();if(!message)return;if(S.preview){addMessage('You · preview note',message);input.value='';return}try{await send('chat',{text:message});if(input.value.trim()===message)input.value=''}catch(e){notify(e.message)}};
$('takeControl').onclick=()=>send('host_claim',{takeover:true}).catch(e=>notify(e.message));
function addMoment(p){const b=el('button','text-button','☆ '+time(p.positionSec));b.title=p.label||'Saved moment';b.onclick=()=>{if(isHost()){S.suppressUntil=0;$('video').currentTime=p.positionSec}else notify('The host controls playback.')};$('moments').append(b);while($('moments').children.length>5)$('moments').firstChild.remove()}
$('mark').onclick=()=>{const p={positionSec:$('video').currentTime||0,label:'A good moment'};if(S.preview)addMoment(p);else send('moment',p).then(()=>notify('Moment saved for your room.')).catch(e=>notify(e.message))};
async function copy(value){try{await navigator.clipboard.writeText(value);notify('Copied. Send it to your people.')}catch{notify('Select the link below and copy it.')}}
$('invite').onclick=()=>{if(S.preview)return showStart();const c=modal('Make room for your people.');paragraph(c,'Send this link. They open it, choose a name, and join you.');const link=location.origin+'/#room='+S.room;const f=field(c,'Invite link','',link);f.readOnly=true;f.className='copy-field';f.onclick=()=>f.select();button(c,'Copy invite link',()=>copy(link));c.append(el('div','room-code',S.room.slice(0,4).toUpperCase()+' '+S.room.slice(4).toUpperCase()));paragraph(c,'They can also enter this code from the home screen. Anyone with the code can join, so share it only with your guests.','fine')};
$('media').onclick=()=>{const c=modal('What are we watching?');paragraph(c,'The original sample is ready now. You can also use a public HTTPS link to a video you are allowed to share.');button(c,'Play the original sample',()=>{closeModal();loadVideo('/media/orbit.mp4','Orbit — a Showcials original')},'secondary');const u=field(c,'Direct video URL','https://example.com/video.mp4'),t=field(c,'Video title','A name for your film');button(c,'Load this video',()=>{let url;try{url=new URL(u.value);if(url.protocol!=='https:')throw Error()}catch{return notify('Use a complete HTTPS video link.')}closeModal();loadVideo(url.href,t.value.trim()||'Your shared video')});paragraph(c,'Use a direct MP4 or compatible HLS (.m3u8) link, not a Netflix, Hulu, or YouTube page. Format, permissions, and browser support still apply.','fine')};
async function loadVideo(url,title){const p={...demoSync(),mediaUrl:S.preview&&url==='/media/orbit.mp4'?(window.ORBIT_DEMO||url):url,mediaTitle:title,runtimeSec:0,format:/\.m3u8(\?|$)/.test(url)?'hls':'mp4'};if(S.preview)applySync(p,true);else{try{await send('sync',p)}catch(e){notify(e.message)}}}
function goHome(){disconnect();S.room='';S.preview=false;S.sync=null;currentMedia='';if(hls){hls.destroy();hls=null}$('video').removeAttribute('src');$('video').load();$('lobby').hidden=false;$('watchroom').hidden=true;if(!window.ORBIT_OFFLINE&&location.protocol!=='file:')history.replaceState(null,'','/');window.scrollTo(0,0);updateGallery();duckMusic()}
$('leave').onclick=goHome;$('home').onclick=goHome;$('start').onclick=showStart;$('join').onclick=()=>showJoin();$('preview').onclick=previewRoom;$('settings').onclick=showSettings;$('help').onclick=showHelp;$('privacy').onclick=showPrivacy;
let musicCtx=null,musicBus=null,musicOn=false,musicNodes=[];
function tone(){if(!musicOn||!musicCtx)return;const t=musicCtx.currentTime,o=musicCtx.createOscillator(),g=musicCtx.createGain();o.frequency.setValueAtTime(659.25,t);o.frequency.exponentialRampToValueAtTime(440,t+.18);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.06,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+.38);o.connect(g).connect(musicBus);o.start(t);o.stop(t+.4);o.onended=()=>{o.disconnect();g.disconnect()}}
function duckMusic(){if(!musicBus||!musicCtx)return;const quiet=S.voice||!$('watchroom').hidden&&!$('video').paused;musicBus.gain.setTargetAtTime(musicOn&&!quiet?pref.volume:0,musicCtx.currentTime,.35)}
async function toggleMusic(){if(musicOn){musicOn=false;pref.music=false;duckMusic();for(const n of musicNodes)try{n.stop()}catch{}musicNodes=[];await musicCtx?.close();musicCtx=null;musicBus=null}else{const C=window.AudioContext||window.webkitAudioContext;if(!C)return notify('Audio is unavailable in this browser.');musicCtx=new C();await musicCtx.resume();musicBus=musicCtx.createGain();musicBus.gain.value=0;musicBus.connect(musicCtx.destination);[73.416,110,146.832,220.04,293.664].forEach((f,i)=>{const o=musicCtx.createOscillator(),g=musicCtx.createGain();o.type='sine';o.frequency.value=f;o.detune.value=i%2?3:-3;g.gain.value=i===0?.12:.025;o.connect(g).connect(musicBus);o.start();musicNodes.push(o)});musicOn=true;pref.music=true;duckMusic();[0,1,2,3].forEach((n)=>{const o=musicCtx.createOscillator(),g=musicCtx.createGain(),t=musicCtx.currentTime+n*.19;o.frequency.value=[293.664,440,587.328,880][n];g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.12,t+.04);g.gain.exponentialRampToValueAtTime(.0001,t+2.4);o.connect(g).connect(musicBus);o.start(t);o.stop(t+2.5)})}$('sound').textContent=musicOn?'♫ Sound on':'♫ Sound off';$('sound').setAttribute('aria-pressed',String(musicOn));savePrefs()}
$('sound').onclick=()=>toggleMusic().catch(()=>notify('Sound could not start. Please try again.'));document.addEventListener('visibilitychange',()=>{if(musicBus&&musicCtx){if(document.hidden)musicBus.gain.setTargetAtTime(0,musicCtx.currentTime,.2);else duckMusic()}});
function showVoice(){if(S.preview)return notify('Start a connected room for voice.');if(S.voice||S.voiceStarting)return stopVoice();const c=modal('Talk together.');paragraph(c,'Your microphone will be heard by people in this room. Use headphones for a clearer conversation. You can turn it off at any time.');const l=el('label','setting','I am 18+ and this is not a child-directed session.'),i=el('input');i.type='checkbox';l.append(i);c.append(l);const b=button(c,'Turn my microphone on',async()=>{if(!i.checked)return notify('Confirm the voice-session notice first.');b.disabled=true;closeModal();await startVoice()});paragraph(c,'Your browser will ask for microphone permission. This app does not record the call; participants may record what they hear.','fine')}
$('talk').onclick=showVoice;
function compatibleCapture(ctx){
 // ORBIT_CAPTURE_FALLBACK_V1: legacy fallback only if AudioWorklet cannot start.
 if(!ctx.createScriptProcessor)throw Error('This browser cannot start microphone capture.');
 const node=ctx.createScriptProcessor(2048,1,1),port={onmessage:null};
 let tail=new Float32Array(0),position=0,frame=new Int16Array(320),used=0;
 const step=ctx.sampleRate/16000;
 node.onaudioprocess=e=>{
  for(let c=0;c<e.outputBuffer.numberOfChannels;c++)e.outputBuffer.getChannelData(c).fill(0);
  const x=e.inputBuffer.getChannelData(0),b=new Float32Array(tail.length+x.length);b.set(tail);b.set(x,tail.length);
  while(position+1<b.length){const n=Math.floor(position),fraction=position-n,v=Math.max(-1,Math.min(1,b[n]*(1-fraction)+b[n+1]*fraction));frame[used++]=Math.round(v*(v<0?32768:32767));if(used===320){port.onmessage?.({data:frame.buffer});frame=new Int16Array(320);used=0}position+=step}
  const consumed=Math.min(Math.floor(position),b.length-1);tail=b.slice(consumed);position-=consumed;
 };
 return {node,port};
}
async function startVoice(){
 // ORBIT_GESTURE_VOICE_V1: start audio inside the user's click, before permission awaits.
 if(!connected())return notify('Join a room first.');
 if(S.voice||S.voiceStarting)return;
 if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia)return notify('Voice needs the secure hosted website and microphone permission.');
 const gen=S.generation,attempt={ctx:null,stream:null};S.voiceStarting=attempt;
 const current=()=>S.generation===gen&&S.voiceStarting===attempt;
 const cleanup=()=>{attempt.stream?.getTracks().forEach(t=>t.stop());if(attempt.ctx&&attempt.ctx.state!=='closed')attempt.ctx.close().catch(()=>{})};
 const bounded=async(p,ms,label)=>{let timer;try{return await Promise.race([p,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error(label)),ms)})])}finally{clearTimeout(timer)}};
 let ctx,stream;
 try{
  ctx=attempt.ctx=new (window.AudioContext||window.webkitAudioContext)();
  const driver=ctx.createConstantSource(),quiet=ctx.createGain();quiet.gain.value=0;driver.connect(quiet).connect(ctx.destination);driver.start();
  const resume=ctx.resume();resume.catch(()=>{});
  $('talk').textContent='Cancel microphone setup';$('voiceStatus').textContent='Waiting for microphone permission…';
  stream=attempt.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});
  if(!current()){cleanup();return}
  $('voiceStatus').textContent='Starting audio…';
  await bounded(resume,8000,'Audio did not start. Tap Talk together again.');
  if(!current()){cleanup();return}
  $('voiceStatus').textContent='Loading microphone capture…';
  let modern=true;try{if(!ctx.audioWorklet)throw Error('AudioWorklet unavailable');await bounded(ctx.audioWorklet.addModule('/capture-worklet.js'),2500,'Capture startup delayed')}catch{modern=false}
  if(!current()){cleanup();return}
  const source=ctx.createMediaStreamSource(stream),fallback=modern?null:compatibleCapture(ctx),worklet=modern?new AudioWorkletNode(ctx,'orbit-capture'):fallback.node,zero=ctx.createGain(),capturePort=modern?worklet.port:fallback.port;
  S.captureEngine=modern?'AudioWorklet':'Compatibility capture';
  zero.gain.value=0;source.connect(worklet).connect(zero).connect(ctx.destination);
  const u=new URL('/voice',location.href);u.protocol=location.protocol==='https:'?'wss:':'ws:';
  u.searchParams.set('room',S.room);u.searchParams.set('clientId',S.id);u.searchParams.set('grant',S.grant);
  const ws=new WebSocket(u);ws.binaryType='arraybuffer';
  const voice={ws,stream,ctx,source,worklet,zero,from:'',times:new Map(),openTimer:null};
  S.voice=voice;S.voiceStarting=null;S.rxFrames=0;S.txFrames=0;duckMusic();
  $('voiceStatus').textContent='Connecting your voice to the room…';
  voice.openTimer=setTimeout(()=>{if(S.voice===voice&&ws.readyState!==1){stopVoice();notify('Voice connection timed out. Tap Talk together to retry.')}},10000);
  ws.onopen=()=>{clearTimeout(voice.openTimer);if(S.voice!==voice){ws.close();return}$('talk').textContent='🎙 Microphone on · turn off';$('talk').setAttribute('aria-pressed','true');$('voiceStatus').textContent='Voice connected. Your microphone is live.'};
  capturePort.onmessage=e=>{if(S.voice!==voice||ws.readyState!==1)return;if(ws.bufferedAmount<65536){ws.send(e.data);S.txFrames++}};
  ws.onmessage=e=>{
   if(S.voice!==voice)return;
   if(typeof e.data==='string'){let p;try{p=JSON.parse(e.data)}catch{return}if(p.type==='voice_frame')voice.from=p.from;if(p.type==='voice_state')$('voiceStatus').textContent='Microphone live · '+(p.roster?.length||1)+' in voice';return}
   if(!(e.data instanceof ArrayBuffer)||e.data.byteLength!==640)return;
   S.rxFrames++;const buffer=ctx.createBuffer(1,320,16000),x=buffer.getChannelData(0),dv=new DataView(e.data);
   for(let j=0;j<320;j++)x[j]=dv.getInt16(j*2,true)/32768;
   const node=ctx.createBufferSource();node.buffer=buffer;node.connect(ctx.destination);
   let t=Math.max(ctx.currentTime+.04,voice.times.get(voice.from)||0);if(t>ctx.currentTime+.4)t=ctx.currentTime+.04;
   node.start(t);if(voice.times.size>24)voice.times.delete(voice.times.keys().next().value);voice.times.set(voice.from,t+.02);node.onended=()=>node.disconnect();
  };
  ws.onerror=()=>{};ws.onclose=()=>{clearTimeout(voice.openTimer);if(S.voice===voice){stopVoice();notify('Voice disconnected. Tap Talk together to retry.')}};
  stream.getAudioTracks().forEach(t=>t.onended=()=>{if(S.voice===voice)stopVoice()});
 }catch(e){
  cleanup();if(S.voiceStarting!==attempt)return;S.voiceStarting=null;
  $('talk').textContent='🎙 Talk together';$('talk').setAttribute('aria-pressed','false');$('voiceStatus').textContent='Microphone is off. Tap Talk together to retry.';
  notify(e.name==='NotAllowedError'?'Microphone permission was not granted. You can still watch and type.':e.message||'Voice could not start. You can still watch and type.');duckMusic();
 }
}
function stopVoice(){const pending=S.voiceStarting;S.voiceStarting=null;if(pending){pending.stream?.getTracks().forEach(t=>t.stop());if(pending.ctx&&pending.ctx.state!=='closed')pending.ctx.close().catch(()=>{})}const v=S.voice;S.voice=null;if(v){clearTimeout(v.openTimer);try{v.ws.close()}catch{}v.stream.getTracks().forEach(t=>t.stop());try{v.source.disconnect();v.worklet.disconnect();v.zero.disconnect()}catch{}v.ctx.close().catch(()=>{})}$('talk').textContent='🎙 Talk together';$('talk').setAttribute('aria-pressed','false');$('voiceStatus').textContent=S.preview?'Voice is available in a connected room.':'Microphone is off. You’re in control.';duckMusic()}
window.addEventListener('beforeunload',()=>{if(S.voice)S.voice.stream.getTracks().forEach(t=>t.stop());S.ws?.close()});
savePrefs();requestAnimationFrame(()=>{updateGallery();scrollChannel(2)});
if((window.ORBIT_OFFLINE||location.protocol==='file:')){$('connection').textContent='Local preview';if(!window.ORBIT_HOME)setTimeout(previewRoom,100)}else{request('/api/health').then(()=>{$('connection').textContent='Ready when you are';$('connection').classList.add('ready')}).catch(()=>{$('connection').textContent='Connection unavailable';notify('The server could not be reached. Try refreshing.')});const code=new URLSearchParams(location.hash.slice(1)).get('room');if(code)setTimeout(()=>showJoin(code),100);else if(location.pathname==='/preview')setTimeout(previewRoom,100)}

// Diagnostic readings are shared only with current room participants.
function reportRoomHealth(){
 if(!connected()||S.preview)return;
 const v=$('video');
 send('stats',{rttMs:S.clock&&S.clock.rtt<60000?S.clock.rtt:0,
  driftMs:S.sync?.mode==='external'?0:Math.max(-60000,Math.min(60000,(v.currentTime-target())*1000)),
  playerState:S.sync?.mode==='external'?'external':v.error?'error':v.ended?'finished':v.paused?'paused':'playing'
 }).catch(()=>{});
}
function showRoomHealth(){
 const c=modal('Check this room');
 paragraph(c,connected()?'Connected to your room.':'Not connected. Start or join a room first.');
 if(S.preview)paragraph(c,'Local preview only: no remote participants or microphone.');
 const entries=Object.entries(S.health||{});
 if(!entries.length)paragraph(c,'No participant readings yet. Readings arrive about every 15 seconds.');
 for(const[key,value]of entries){
  paragraph(c,key+' · '+(value.kind==='roku'?'Roku client':'Browser client'));
  const age=(serverNow()-value.updatedAt)/1000;
  paragraph(c,age>45?'Reading expired.':value.playerState+' · network '+Math.round(value.rttMs)+' ms · reported difference '+(value.driftMs/1000).toFixed(2)+' seconds.','fine');
 }
 paragraph(c,S.voice?'Your microphone session is connected. Received '+S.rxFrames+' frames; sent '+S.txFrames+' frames.':'Your microphone is off.');
 paragraph(c,'Client-reported readings are diagnostics, not confirmation that an official streaming app or physical remote was tested. No readings are saved.','fine');
 button(c,'Refresh readings',()=>{reportRoomHealth();showRoomHealth()},'secondary');
}
const healthButton=el('button','soft','Check connection');healthButton.id='roomHealth';healthButton.onclick=showRoomHealth;document.querySelector('.room-tools').append(healthButton);
